# Generated by Django 5.0.6 on 2024-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_image_alter_user_fav_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
