# Generated by Django 5.0.6 on 2024-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd')], default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('manager', 'Manager')], default='student', max_length=10),
        ),
    ]
