# Generated by Django 5.0.6 on 2024-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_class_name_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_name',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('manager', 'Manager')], default='1', max_length=7),
        ),
    ]
