# Generated by Django 5.0.6 on 2024-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_classes_alter_user_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='student_count',
            field=models.IntegerField(),
        ),
    ]
