# Generated by Django 5.0.6 on 2024-07-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_classes_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classes'),
        ),
    ]
