# Generated by Django 5.0.6 on 2024-07-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_classes_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='class_name',
            new_name='class_id',
        ),
    ]
