# Generated by Django 5.0.6 on 2024-07-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_class_name_user_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='class_id',
            new_name='_class',
        ),
    ]
