# Generated by Django 5.0.6 on 2024-07-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_class_id_user__class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_class',
            new_name='clas',
        ),
    ]
